### ISSUE TITLE
Temporal Coherence Threshold

### ISSUE THREAD

**Issue by bbuzz31** [insarlab/MintPy#292]
Hi, 
Just a small confusion.
`mintpy.networkInversion.minTempCoh  = 0.0` sets the value to the default (0.7) which causes results other than what I expected.
It's stated in the processing messages but possible for it to be overlooked.
Thanks,
Brett

**Comment by yunjunz** [comment]
Thank you @bbuzz31 for pointing it out, I agree. The confusion is now fixed. A classic example of why we should always use `if x is None` instead of `if not x`!

**Comment by bbuzz31** [comment]
Hi @yunjunz thanks for addressing this, and yes I agree indeed!
Unfortunately, it looks like the line you changed in #293 didn't seem to fix the problem. 
My guess is it's not liking the `< vmin` on line 168 (vmin == 0)

**Comment by yunjunz** [comment]
Hi @bbuzz31, could you elaborate more on how this does not fix your problem?

From my testing with `mintpy.networkInversion.minTempCoh = 0.0`, everything seems reasonable: all pixels are selected, except for those in shadow mask.

**Comment by bbuzz31** [comment]
Sorry for the confusion @yunjunz; you're right, the problem is fixed with #293.
